# Generated by Django 5.2 on 2025-07-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreport',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
